# 반복문
- 에러 확률 감소, 불필요한 작업 감수 위함.

for 반복문
- for→각각의 상황에서 라는 의미로 사용됨.
- ‘for 변수 in 범위’ 가 기본형태 / 범위=반복할 범위, 횟수로 설정x
- : → 다음 단락에 코드블럭이 올 것임을 예언하는 표시

In [7]:
for i in range(1,6):
    print(123)
    print(456)
    print(789)

123
456
789
123
456
789
123
456
789
123
456
789
123
456
789


In [10]:
# IndentationError → 들여쓰기 에러
for i in range(1,6):
    print(123)
print(456)
    print(789)

IndentationError: unexpected indent (317452299.py, line 4)

In [11]:
for i in range(1,6):
    print(123)
print(456)
print(789)

123
123
123
123
123
456
789


In [12]:
for i in[9,8,5,2,1]:
    print(i)

9
8
5
2
1


range 함수 → for 반복문 사용 시 가장 많이 사용(거의 대부분)
- 파이썬에서 기본값은 생략 가능한 표현
- stop: 파이썬에서 (n,n-1)로 범위 인식하기에 n+1로 입력해야 함.
- 펼쳐보기 → for 반복문에 넣기, list함수 안에 넣기
- start 없이, stop, step 만 사용x / 셋다 적기, stop만 적기 start, stop만 적기
- 실수x 정수만 입력 가능
- input함수는 문자열로만 인식



In [1]:
# [9,5,4,2] list를 range 함수 대신 사용 가능.
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [18]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
list(range(2, 25, 2))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]

In [24]:
list(range(-13, -7))

[-13, -12, -11, -10, -9, -8]

In [25]:
list(range(3, 29, 3))

[3, 6, 9, 12, 15, 18, 21, 24, 27]

In [49]:
# 실습1: 25이하 자연수, 2배수로 / 2: -8~-13까지 정수 / 3: 29까지 자연수, 3의 배수 / 4: 0.1~0.5 순서대로 표현
for i in(range(2, 26, 2)):
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24


In [31]:
for i in(range(-13,-7)):
    print(i)

-13
-12
-11
-10
-9
-8


In [50]:
for i in(range(-8, -14, -1)):
    print(i)

-8
-9
-10
-11
-12
-13


In [54]:
for i in(range(3, 30, 3)):
    print(i)

3
6
9
12
15
18
21
24
27


In [67]:
for i in(range(1 ,6, 1)):
    print(i/10)

0.1
0.2
0.3
0.4
0.5


In [68]:
for i in [0.1, 0.2, 0.3, 0.4 , 0.5]:
    print(i)

0.1
0.2
0.3
0.4
0.5


In [90]:
input_number=int(input('숫자 하나를 입력해 주세요:'))

for i in range(2, input_number+1, 2):
    print(i)

숫자 하나를 입력해 주세요:12
2
4
6
8
10
12


while 반복문
- 트리거x는 무한 반복
- ind → 자유롭게 편한 문자로 변경 가능
- while ‘지정 문자’ “관계비교(같다, 크다, 작다, 크거나 같다 등)” ‘지정 문자’:
- vs for은 범위 조절 0
- 공통 명령문 → 현재 상황과 관계 없이 명령 실행 / 명령어만 단락에 작성
- True, False로만 조건 판단 가능, for 같이 범위 조건 판단 불가능하기에 조건문을 추가로 작성해주어야 함.


In [91]:
ind = 0

while ind < 10:
    print('hello')
    ind+= 1

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello


In [109]:
input_number=int(input('숫자 하나를 입력해 주세요:'))

start_number = 2
while start_number <= input_number:
    print(start_number)
    start_number+=2

숫자 하나를 입력해 주세요:20
2
4
6
8
10
12
14
16
18
20


- continue: 뒤에  코드 무시하고 다음 루프 실행 / 특정 상황에서만 실행되는 코드 만들 때 사용
- break: 뒤에 코드 무시하고 무조건 종료 / while 반복문 컨트롤하기 위해 사용
- pass: 아무것도 안함..(원래 코드 그대로 실행) 
/ 아무것도 안함을 명시하기 위해 사용, 코드가 완성되지 않은 상황에서 에러를 내지 않고 임시로 코드 동작 위해(가독성)

In [113]:
for i in range(1,11):
    print(i)
    pass
    print('---')

1
---
2
---
3
---
4
---
5
---
6
---
7
---
8
---
9
---
10
---


# 다중 루프

In [119]:
for i in range(9,6,-1):
    print(i)
    
    for j in range(9,6,-1):
        print(j)

9
9
8
7
8
9
8
7
7
9
8
7


In [122]:
i=0

while i < 3:
    print(i)
    i+=1
    
    j=5
    while j>3:
        print(j)
        j-=1

0
5
4
1
5
4
2
5
4


In [141]:
list1= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [150]:
list1[0][1]

2

In [186]:
for i in list1:
    for j in i:
        print(j, end=' ')

1 2 3 4 5 6 7 8 9 

In [173]:
for i in list1:
    for j in i:
        print(j, end=' ')
        
    print()

1 2 3 
4 5 6 
7 8 9 


In [191]:
print(3)
print()
print(3)

3

3


In [240]:
for i in list1:
    for j in i:
        print(j, end=' ')
        
    print()
    

1 2 3 
4 5 6 
7 8 9 


# 조건문(if)
- elif: 그게 아니고 ~라면
- if문 몇 개든 사용 숫자는 상관 없지만, if-elif-else 순으로 작성되어야 함. 앞에 if문 없으면 뒤 함수 사용 불가
- if문+not: not의 경우 해당 논리 반대로 해석.
- if not a==100 → a는 100과 일치하지 않는다.


In [261]:
x=12345

In [262]:
if x==123:
    print('x는 123입니다')
    
elif x== 1234:
    print('x는 1234임')
    
else:
    print('둘 다 아님!')

둘 다 아님!


In [263]:
a=99
b=88

In [265]:
if a==99 and b==88:
    print('99와 88이 있어요')

99와 88이 있어요


In [267]:
if a==99 or b==88:
    print('둘 중 하나는 88이다')

둘 중 하나는 88이다


In [269]:
if not a==100:
    print('100')

100


In [305]:
x=1

In [306]:
for i in range(1,6):
    x*=i

In [307]:
x

120

In [309]:
y=int(input('숫자 하나:'))

숫자 하나:6


In [312]:
y=int(input('숫자 하나:'))

for i in range(2, y+1, 2):
    x=1
    for j in range(1, i+1):
        x*=j
    print(f'{i}!의 값은 {x}입니다')

숫자 하나:6
2!의 값은 2입니다
4!의 값은 24입니다
6!의 값은 720입니다


# 포맷팅
- 변수를 직접 변화 없이 실시간 변경 가능하게 함.

In [315]:
x=124
y=45.67
z=['a','s','d','f']

In [318]:
print("x는",x,"이고, y는 ", y, "이고 z는 ", z ,"입니다.")

x는 124 이고, y는  45.67 이고 z는  ['a', 's', 'd', 'f'] 입니다.


In [329]:
print('x는 %d이고, y는 %.2f이고, z는 %s입니다.' %(x,y,z))

x는 124이고, y는 45.67이고, z는 ['a', 's', 'd', 'f']입니다.


In [322]:
print("x는 {}이고, y는 {}이고, z는 {}입니다." .format(x,y,z))

x는 124이고, y는 45.67이고, z는 ['a', 's', 'd', 'f']입니다.


In [325]:
print("x는 {}이고, y는 {}이고, z는 {}입니다." .format(x,y,z))

x는 124이고, y는 45.67이고, z는 ['a', 's', 'd', 'f']입니다.


In [326]:
print(f"x는 {x}이고, y는 {y}이고, z는 {z}입니다.")

x는 124이고, y는 45.67이고, z는 ['a', 's', 'd', 'f']입니다.


# 넘파이
- 정적 배열, 사이즈가 정해져있음. 확장, 축소x / 자료형 통일 ex) 한 개 실수면 데이터 전체 실수 / 브로드캐스팅(일괄 연산) 지원됨

In [330]:
import numpy as np

In [333]:
arr=np.array([1,2,3,4,5])

In [334]:
type(arr)

numpy.ndarray

In [335]:
arr[2]

3

In [336]:
arr[1:5]

array([2, 3, 4, 5])

In [337]:
arr*4

array([ 4,  8, 12, 16, 20])

In [338]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3=np.array([5,6,7])

In [339]:
arr2.dot(arr3)

array([ 38,  92, 146])

인덱싱 / 슬라이싱
- 인덱싱→ 원소 1개 추출(해당 좌표를 찾음)/ 슬라이싱 → 원소 여러 개 추출(=범위 추출/a좌표부터b좌표까지 해당되는 모든 값을 찾을 수 있도록 하는 데이터)
- 슬라이싱[시작 인덱스, 종료 인덱스, 인덱스 간격] / :: → 전 구간 포함



In [342]:
list1=[1,2,3,4,5,6,7,8,9,0]

In [343]:
list1[:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

In [344]:
list1[1:5:2]

[2, 4]

In [345]:
list1[-4]

7

In [346]:
list1[-4:]

[7, 8, 9, 0]

In [352]:
list1[-4::-1]

[7, 6, 5, 4, 3, 2, 1]

In [356]:
list1[::-1]

[0, 9, 8, 7, 6, 5, 4, 3, 2, 1]

넘파이 파일 읽기, 쓰기
- np.save('./f1.npy',arr) : ./ → 동일 경로를 표현하기 위해 사용 ../ → 사용 폴더 위 폴더 의미

In [357]:
np.save('./f1.npy',arr)

In [366]:
np.save('C:/Users/BIG3-06/Documents/빅데이터/f2.npy',arr)

In [367]:
np.load('./f1.npy')

array([1, 2, 3, 4, 5])

In [368]:
np.savez('.f1.npz',A=arr)

In [370]:
np.load('.f1.npz')['A']

array([1, 2, 3, 4, 5])

# 판다스
- c ->열, 세로. column네임= 헤더 / r →행, 가로, row네임=인덱스
- 1차원 데이터 -> 세로로 한줄 / 다차원 데이터 -> 가로로 여러줄
- 모든 자료형 인덱싱 시작은 가로부터

In [371]:
import pandas as pd

In [372]:
pd.DataFrame([1,2,3,4,5])

0
0  1
1  2
2  3
3  4
4  5

In [377]:
np.array([[1,2,3,4,5],[6,7,8,9,0],[7,8,9,5,3]])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0],
       [7, 8, 9, 5, 3]])

In [378]:
df=pd.DataFrame([[1,2,3,4,5],[6,7,8,9,0],[7,8,9,5,3]])

In [379]:
df

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0
2  7  8  9  5  3

- 판다스에서 인덱싱: df[열][행] / df.loc(행, 열)

In [382]:
df[1][0]

2

In [384]:
df.loc[1][0]

6

- 판다스에서 슬라이싱: df.loc[행, 열] /행,열에 대해 : 로 범위 지정 가능

In [385]:
df[1:3]

0  1  2  3  4
1  6  7  8  9  0
2  7  8  9  5  3

In [386]:
df.loc[:,1:3]

1  2  3
0  2  3  4
1  7  8  9
2  8  9  5

In [390]:
df.loc[1:3, 1:3]

1  2  3
1  7  8  9
2  8  9  5

In [391]:
df.iloc[:,1:3]

1  2
0  2  3
1  7  8
2  8  9

In [392]:
df

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0
2  7  8  9  5  3

In [396]:
df[2]*4

0    12
1    32
2    36
Name: 2, dtype: int64

In [397]:
df*4

0   1   2   3   4
0   4   8  12  16  20
1  24  28  32  36   0
2  28  32  36  20  12

In [398]:
df.to_csv('./df.csv')

In [400]:
pd.read_csv('./df.csv',index_col=0)

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0
2  7  8  9  5  3

In [401]:
pd.read_csv('./df.csv',index_col=0, header=2)

6  7  8  9  0
1               
2  7  8  9  5  3

In [407]:
df.to_csv('./df.csv', index=False)

In [408]:
pd.read_csv('./df.csv')

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0
2  7  8  9  5  3

In [409]:
df.to_excel('./df.xlsx')

In [410]:
pd.read_excel('./df.xlsx')

Unnamed: 0  0  1  2  3  4
0           0  1  2  3  4  5
1           1  6  7  8  9  0
2           2  7  8  9  5  3

In [412]:
pd.read_excel('./df.xlsx', comment='#', index_col=0)

0  1  2  3  4
0  1  2  3  4  5
1  6  7  8  9  0
2  7  8  9  5  3

# 함수

In [417]:
a= 1+1

In [418]:
b= print(1+1)

2


In [419]:
a

2

In [421]:
type(b)

NoneType

In [422]:
def func1(x):
    return x+10

In [423]:
func1(10)

20

In [424]:
def func2(x):
    return x+10
    return x+100

In [425]:
func2(10)

20

In [426]:
def func3(x):
    if x%2==0:
        return x+10
    return x+100

In [427]:
func3(10)

20

In [428]:
func3(11)

111

In [429]:
def func4(x):
    return x+10, x+100

In [431]:
func4(10)

(20, 110)

In [432]:
q,w = func4(10)

In [433]:
q

20

In [435]:
w

110

+인터프리터 방식:

- 실행 시점에서 한 줄씩 코드를 해석하고 실행: 인터프리터는 소스 코드를 직접 실행하며, 코드를 한 줄씩 해석하고 실행합니다. 각 줄이 실행되기 전에 코드가 컴파일되지 않고, 실제 실행 시에 해석되기 때문에 빠르게 수정 및 실행이 가능합니다.
- 실행 중에 에러 확인 가능: 코드를 한 줄씩 실행하기 때문에 오류가 발생하면 해당 줄에서 바로 에러를 확인할 수 있습니다.
- 대표적인 예시: Python, Ruby, JavaScript (일부 환경에서는 인터프리터 방식으로 동작), PHP 등.

+스크립트 방식:

- 전체 코드를 미리 컴파일한 후 실행: 스크립트 언어는 보통 전체 코드를 한 번에 미리 컴파일한 후에 실행합니다. 이로써 실행 시간이 빠를 수 있습니다.
- 컴파일 단계에서 에러 확인: 코드를 실행하기 전에 먼저 전체 코드를 컴파일하므로 실행 중에 발생하는 오류가 아니더라도 컴파일 시에 발견할 수 있습니다.
- 대표적인 예시: Java, C, C++, Go, Rust 등.


# 복습

In [3]:
for i in range(1, 6):
    print(i, end=' ')

1 2 3 4 5 

In [8]:
for i in range(1,11):
    print('hello!', end=' ')

hello! hello! hello! hello! hello! hello! hello! hello! hello! hello! 

In [15]:
for i in range(2, 26, 2):
    print(i, end=' ')

2 4 6 8 10 12 14 16 18 20 22 24 

In [20]:
for i in range(-8, -14, -1):
    print(i, end=' ')

-8 -9 -10 -11 -12 -13 

In [24]:
for i in range(3, 30, 3):
    print(i, end=' ')

3 6 9 12 15 18 21 24 27 

In [27]:
for i in range(1, 6):
    print(i/10, end=' ')

0.1 0.2 0.3 0.4 0.5 

In [36]:
s_num=int(input('숫자 하나 입력'))

for i in range(2, int(s_num)+1, 2):
    print(i)
    

숫자 하나 입력6
2
4
6


In [43]:
s_num=int(input('숫자 하나 입력'))

for i in range(1, int(s_num)+1, 2):
    print(i)

숫자 하나 입력6
1
3
5


In [45]:
ind=0

while ind<10:
    ind+=1
    print(ind, end=' ')

1 2 3 4 5 6 7 8 9 10 

In [55]:
k_num=int(input('숫자 하나 입력'))

ind=2
while ind <= k_num:
    print(ind)
    ind+=2

숫자 하나 입력6
2
4
6


In [56]:
k_num=int(input('숫자 하나 입력'))

ind=1
while ind <= k_num:
    print(ind)
    ind+=2

숫자 하나 입력6
1
3
5


In [58]:
k_num=int(input('숫자 하나 입력'))

ind=1
while ind <= k_num:
    print(ind)
    break
    ind+=2

숫자 하나 입력6
1


In [59]:
k_num=int(input('숫자 하나 입력'))

ind=1
while ind <= k_num:
    print(ind)
    pass
    ind+=2

숫자 하나 입력6
1
3
5


In [60]:
list1= [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [61]:
list1[0][1]

2

In [75]:
for i in list1:
    for j in i:
        print(j, end=" ")

1 2 3 4 5 6 7 8 9 

In [77]:
for i in list1:
    for j in i:
        print(j, end=' ')
    print()

1 2 3 
4 5 6 
7 8 9 


In [96]:
s_num=int(input('숫자 하나 입력'))

for i in range(1, s_num+1):
    if i%2==0:
        x=1
        for j in range(1, i+1):
            x*=j
        print(f'{i}의 값은 {x}입니다.')

숫자 하나 입력6
2의 값은 2입니다.
4의 값은 24입니다.
6의 값은 720입니다.


In [98]:
s_num=int(input('숫자 하나 입력'))

for i in range(2, s_num+1, 2):
    x=1
    for j in range(1, i+1):
        x*=j
    print(f'{i}!의 값은 {x}입니다.')

숫자 하나 입력6
2의 값은 2입니다.
4의 값은 24입니다.
6의 값은 720입니다.


In [99]:
import numpy as np

In [101]:
arr=np.array([1,2,3,4,5])

In [102]:
arr

array([1, 2, 3, 4, 5])

In [103]:
arr+3

array([4, 5, 6, 7, 8])

In [104]:
arr[-2]

4

In [105]:
arr[1:5:2]

array([2, 4])

In [107]:
arr[-3:]

array([3, 4, 5])

In [115]:
arr[-3::-1]

array([3, 2, 1])

In [116]:
import pandas as pd

In [139]:
df=pd.DataFrame([[1,2,3,4,5],[6,7,8,9,0]])

In [185]:
df

a  b  c  d  e
ㄱ  1  2  3  4  5
ㄴ  6  7  8  9  0

In [190]:
df.loc['ㄱ']['a']

1

In [151]:
df.columns = ['a', 'b', 'c', 'd', 'e']
df.index = ['ㄱ', 'ㄴ']

In [152]:
df

a  b  c  d  e
ㄱ  1  2  3  4  5
ㄴ  6  7  8  9  0

In [154]:
df.to_excel('C:/Users/BIG3-06/Documents/빅데이터.xlsx')

In [164]:
df=pd.read_excel('C:/Users/BIG3-06/Documents/빅데이터.xlsx', index_col=0)

In [165]:
df

a  b  c  d  e
ㄱ  1  2  3  4  5
ㄴ  6  7  8  9  0

In [200]:
df.iloc[1:2, 1:2]

b
ㄴ  7